### ISSUE TITLE
justauthstarter在 springboot3.2.4中 自动装配失效

### ISSUE THREAD

**Issue by fanjia1024** [justauth/justauth-spring-boot-starter#23]
justauthstarter 1.4.0 在 springboot3.2.4中 自动装配失效

**Comment by fanjia1024** [comment]
Action:

Consider defining a bean of type 'com.xkcoding.justauth.AuthRequestFactory' in your configuration.

**Comment by wangyiidii** [comment]
使用springboot3自动装配的方式即可，或者看[最新的pr](https://github.com/justauth/justauth-spring-boot-starter/pull/24)

**Comment by fanjia1024** [comment]
我已经更新在我们的私有仓库里面  包含对 pom 中的相关组件的升级都做了更改
