### ISSUE TITLE
redisTemplet冲突

### ISSUE THREAD

**Issue by activekou** [justauth/justauth-spring-boot-starter#5]
使用时需要手动移除一个  如果留给自己实现是否更方便

**Comment by xkcoding** [comment]
justauth-spring-boot-starter 里对 RedisTemplate 的 Bean 命名为 `justAuthRedisCacheTemplate`
这边建议您添加对自己注入的也提供一个命名，后续注入通过 `@Qualifier` 区分下
暂时没想到更好的处理方式，如果您有更好的方式，欢迎 PR
